import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Cart from '../../components/Cart';

const index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Cart />
    </div>
  );
};

export default index;
