import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import ProductDetails from '../../components/ProductDetails';

const index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Product Details</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ProductDetails />
    </div>
  );
};

export default index;
