import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';

const Home: any = () => {
  Home.layout = 'L1';
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      Fuck
    </div>
  );
};

export default Home;
