import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Store from '../components/Store';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Store />
    </div>
  );
};

export default Home;
